# Generated by Django 4.0 on 2021-12-15 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('about_subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=3)),
                ('number_of_students', models.IntegerField()),
                ('training_profile', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='LectureHalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_hall_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=45)),
                ('lesson_index_number', models.DecimalField(decimal_places=2, max_digits=2)),
                ('day_of_the_week', models.CharField(max_length=12)),
                ('is_busy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.DecimalField(decimal_places=10, max_digits=10)),
                ('qualification', models.CharField(max_length=20)),
                ('study_load', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20)),
                ('lesson_number', models.IntegerField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NIR_UD.classes')),
                ('lecture_hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NIR_UD.lecturehalls')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NIR_UD.academicsubjects')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.DecimalField(decimal_places=10, max_digits=10)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone_number', models.DecimalField(decimal_places=10, max_digits=10)),
                ('address', models.TextField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NIR_UD.classes')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('homework_text', models.TextField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NIR_UD.classes')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NIR_UD.academicsubjects')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NIR_UD.teachers'),
        ),
        migrations.CreateModel(
            name='AverageScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_score', models.FloatField(max_length=3)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NIR_UD.classes')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NIR_UD.students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NIR_UD.academicsubjects')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('is_appeared', models.BooleanField()),
                ('student_mark', models.DecimalField(decimal_places=1, max_digits=1)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NIR_UD.classes')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NIR_UD.students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NIR_UD.academicsubjects')),
            ],
        ),
    ]
