# Generated by Django 4.0 on 2021-12-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NIR_UD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicperformance',
            options={'verbose_name': 'Оценка за урок', 'verbose_name_plural': 'Таблица успеваемости'},
        ),
        migrations.AlterModelOptions(
            name='academicsubjects',
            options={'verbose_name': 'Учебный предмет', 'verbose_name_plural': 'Таблица учебных предметов'},
        ),
        migrations.AlterModelOptions(
            name='averagescore',
            options={'verbose_name': 'Средний балл', 'verbose_name_plural': 'Таблица средних баллов'},
        ),
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Таблица классов'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Таблица домашних заданий'},
        ),
        migrations.AlterModelOptions(
            name='lecturehalls',
            options={'verbose_name': 'Занятость аудитории', 'verbose_name_plural': 'Таблица занятости аудиторий'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Таблица учеников'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Таблица учителей'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Расписание уроков'},
        ),
    ]
