# Generated by Django 4.0 on 2021-12-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIR_UD', '0003_alter_academicperformance_lesson_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicperformance',
            name='student_mark',
            field=models.IntegerField(max_length=1),
        ),
    ]
