# Generated by Django 4.0 on 2021-12-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIR_UD', '0004_alter_academicperformance_student_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicperformance',
            name='student_mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='parent_phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
